### ISSUE TITLE
Composer RuntimeException when running yii3 app template in server, not from ./yii serve

### ISSUE THREAD

**Issue by wiperawa** [yiisoft/app#24]
### What steps will reproduce the problem?
If you setup app template as a vhost and run in apache server, not as ./yii server, with composer installed locally on machine, getting RuntimeException.

### What is the expected result?

index page of Yii3 app template

### What do you get instead?

Fatal error: Uncaught RuntimeException: The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly in /srv/www/vhosts/yii3app/vendor/composer/composer/src/Composer/Factory.php:648 Stack trace:
 #0 /srv/www/vhosts/yii3app/vendor/composer/composer/src/Composer/Factory.php(69): Composer\Factory::getUserDir() 
#1 /srv/www/vhosts/yii3app/vendor/composer/composer/src/Composer/Factory.php(160): Composer\Factory::getHomeDir() 
#2 /srv/www/vhosts/yii3app/vendor/composer/composer/src/Composer/Factory.php(303): Composer\Factory::createConfig(Object(Composer\IO\ConsoleIO), '/srv/www/vhosts...') 
#3 /srv/www/vhosts/yii3app/vendor/yiisoft/composer-config-plugin/src/Plugin.php(76): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, true, '/srv/www/vhosts...', false) 
#4 /srv/www/vhosts/yii3app/vendor/yiisoft/composer-config-plugin/src/Builder.php(71): Yiisoft\Composer\Config\Plugin::buildAllConfigs('/srv/www/vhosts...') 
#5 /srv/www/vhosts/yii3app/public/index.php(33): Yiisoft\Composer\Config\ in /srv/www/vhosts/yii3app/vendor/composer/composer/src/Composer/Factory.php on line 648

### Additional info

Obviously, Composer cant find HOME or COMPOSER_HOME Env variable, as there is no such env, setted globally for all processes. 

setting it in /public/index.php as : putenv("COMPOSER_HOME=\$HOME/.config/composer") solve the issue

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4.7
| Operating system |Linux

**Comment by samdark** [comment]
https://github.com/yiisoft/composer-config-plugin/pull/88
