### ISSUE TITLE
Add swoole , roadruner entryscript

### ISSUE THREAD

**Issue by pigochu** [yiisoft/app#30]
I have studied yiisoft/docs, but I still can't make yiisoft/app work in swoole, could it add the entry script of swoole and roadrunner to this project ?

**Comment by samdark** [comment]
What's the problem? Doesn't https://github.com/yiisoft/docs/blob/master/guide/en/tutorial/using-yii-with-swoole.md work?

**Comment by pigochu** [comment]
Because I am new to Yii3, I still don’t know the whole architecture very well, so I hope to have a relatively simple example to get started and learn quickly

```
pigo@PIGO-PC(18.04):~/projects/yii3app$ php swoole-server.php 
Assembling config files
PHP Warning:  require(/home/pigo/projects/src/globals.php): failed to open stream: No such file or directory in /home/pigo/projects/yii3app/swoole-server.php on line 17
Warning: require(/home/pigo/projects/src/globals.php): failed to open stream: No such file or directory in /home/pigo/projects/yii3app/swoole-server.php on line 17
PHP Fatal error:  require(): Failed opening required '/home/pigo/projects/src/globals.php' (include_path='.:/usr/share/php') in /home/pigo/projects/yii3app/swoole-server.php on line 17
Fatal error: require(): Failed opening required '/home/pigo/projects/src/globals.php' (include_path='.:/usr/share/php') in /home/pigo/projects/yii3app/swoole-server.php on line 17

========= I remove require globals.php ================

pigo@PIGO-PC(18.04):~/projects/yii3app$ php swoole-server.php 
Assembling config files
PHP Fatal error:  Uncaught Yiisoft\Factory\Exceptions\NotFoundException: No definition for Psr\Http\Message\ResponseFactoryInterface in /home/pigo/projects/yii3app/vendor/yiisoft/di/src/Container.php:232
```

**Comment by samdark** [comment]
`globals.php` was removed. Remove it from your entry script as well. I've updated the guide.

**Comment by pigochu** [comment]
still not work
~~~
PHP Fatal error:  Uncaught Yiisoft\Factory\Exceptions\NotFoundException: No definition for Psr\Http\Message\ResponseFactoryInterface in /home/pigo/projects/yii3app/vendor/yiisoft/di/src/Container.php:226
Stack trace:
#0 /home/pigo/projects/yii3app/vendor/yiisoft/di/src/Container.php(203): Yiisoft\Di\Container->buildPrimitive()
#1 /home/pigo/projects/yii3app/vendor/yiisoft/di/src/Container.php(155): Yiisoft\Di\Container->buildInternal()
~~~
I modify some code
~~~php
$container = new Container(
    require Builder::path('web')
);
~~~
to
~~~
$container = new Container(
    require Builder::path('web'),
    require Builder::path('providers-web')
);
~~~

but got other error.


![image](https://user-images.githubusercontent.com/1013744/87489719-49833e80-c676-11ea-9292-0e3b377c4844.png)

What i care about is

If I want to design a project that will work with php-fpm and swoole in the future
Is it complicated?

**Comment by samdark** [comment]
> Is it complicated?

Kind of. Entry point is easy part. I'll get back to it and fix the guide. Currently it seems that it's outdated :( But that's not the major issue that is easily fixable. What's more complicated is the "worker serves many requests" model i.e. https://github.com/yiisoft/docs/blob/master/guide/en/tutorial/using-with-event-loop.md. If your app isn't ready for it, you'll expect all kinds on complicated issues.
